// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRxUZ1MF8kkp7eKjT5L65_JNq6Jf6xOBQ',
    appId: '1:458404350398:web:b35f60acfe48f1e6cb11ef',
    messagingSenderId: '458404350398',
    projectId: 'flutter-drink-recipe-book-01',
    authDomain: 'flutter-drink-recipe-book-01.firebaseapp.com',
    storageBucket: 'flutter-drink-recipe-book-01.appspot.com',
    measurementId: 'G-0HW93KRHFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVxofmhNJvRgDowZxhT0ShYmltw7jmPDE',
    appId: '1:458404350398:android:9338f07dbabbf43bcb11ef',
    messagingSenderId: '458404350398',
    projectId: 'flutter-drink-recipe-book-01',
    storageBucket: 'flutter-drink-recipe-book-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLdjBOZFJE-V5fcLGYSRElurCclnUCrdA',
    appId: '1:458404350398:ios:f46da38243a46e0acb11ef',
    messagingSenderId: '458404350398',
    projectId: 'flutter-drink-recipe-book-01',
    storageBucket: 'flutter-drink-recipe-book-01.appspot.com',
    iosBundleId: 'com.example.flutterDrinkRecipeBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLdjBOZFJE-V5fcLGYSRElurCclnUCrdA',
    appId: '1:458404350398:ios:263998152486b670cb11ef',
    messagingSenderId: '458404350398',
    projectId: 'flutter-drink-recipe-book-01',
    storageBucket: 'flutter-drink-recipe-book-01.appspot.com',
    iosBundleId: 'com.example.flutterDrinkRecipeBook.RunnerTests',
  );
}
